In [23]:
import pandas as pd
df =pd.read_csv(r'C:\Users\Mr BALADI\Desktop\fin sas\london_merged.csv')
df

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [24]:
df.rename(columns={'cnt':'Nombre de trajets',
                      't1':'Température réelle (°C)',
                      't2':'Température ressentie (°C)',
                      'hum':'Humidité',
                      'wind_speed':'Vitesse du vent (km/h)',
                      'weather_code':'Météo',
                      'season':'Saison',
                    })

,timestamp,Nombre de trajets,Température réelle (°C),Température ressentie (°C),Humidité,Vitesse du vent (km/h),Météo,is_holiday,is_weekend,Saison
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [25]:
df["Humidité"] = df["Humidité"] / 100

KeyError: 'Humidité'

In [ ]:
#df['Saison'].unique()
#df['Météo'].unique()

#df['Saison'] = df['Saison'].map({0: 'Printemps', 1: 'Été', 2: 'Automne', 3: 'Hiver'})
#df.Saison = df.Saison.astype(str)

In [ ]:
#df['Saison'].unique() # pour aficher le nombre repete 
#saison_map={0: "Printemps",
            #1: "Été", 
            #2: "Automne", 
           # 3: "Hiver"}
         
#df["Saison"]=df["Saison"].map(saison_map)
df['Saison'] = df['Saison'].map({0: 'Printemps', 1: 'Été', 2: 'Automne', 3: 'Hiver'})
#df                                
#df['Météo'].unique # pour aficher le nombre repete
df['Météo']=df['Météo'].map({1:'Clair', 2:'Nuages épars', 3:'Nuages fragmentés', 4:'Couvert', 10:'Pluie', 8:'Pluie avec orage', 26:'Neige'})
#df[(df["Humidité"]<0)| (df["Humidité"]>1)]
df

,timestamp,Nombre de trajets,Température réelle (°C),Température ressentie (°C),Humidité,Vitesse du vent (km/h),Météo,is_holiday,is_weekend,Saison
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Nuages fragmentés,0.0,1.0,Hiver
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clair,0.0,1.0,Hiver
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clair,0.0,1.0,Hiver
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clair,0.0,1.0,Hiver
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clair,0.0,1.0,Hiver
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,0.810,19.0,Nuages fragmentés,0.0,0.0,Hiver
17410,2017-01-03 20:00:00,541,5.0,1.0,0.810,21.0,Couvert,0.0,0.0,Hiver
17411,2017-01-03 21:00:00,337,5.5,1.5,0.785,24.0,Couvert,0.0,0.0,Hiver
17412,2017-01-03 22:00:00,224,5.5,1.5,0.760,23.0,Couvert,0.0,0.0,Hiver
17413,2017-01-03 23:00:00,139,5.0,1.0,0.760,22.0,Nuages épars,0.0,0.0,Hiver

In [ ]:
df.to_excel("london_bikes_final.xlsx")
df.to_csv("london_bikes_final.csv")